/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cdm.resturant;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Noor
 */
public class Main_Page extends javax.swing.JFrame {

    /**
     * Creates new form Main_Page
     */
    public Main_Page() {
        initComponents();
         Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        meals = new javax.swing.JButton();
        soft = new javax.swing.JButton();
        alcohol = new javax.swing.JButton();
        sandwich = new javax.swing.JButton();
        shakes = new javax.swing.JButton();
        dessert = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO THE MAIN PAGE");

        meals.setBackground(new java.awt.Color(255, 255, 255));
        meals.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        meals.setForeground(new java.awt.Color(0, 102, 102));
        meals.setText("MEALS");
        meals.setBorder(null);
        meals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealsMouseClicked(evt);
            }
        });
        meals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealsActionPerformed(evt);
            }
        });

        soft.setBackground(new java.awt.Color(255, 255, 255));
        soft.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        soft.setForeground(new java.awt.Color(0, 102, 102));
        soft.setText("SOFT DRINKS");
        soft.setBorder(null);
        soft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                softMouseClicked(evt);
            }
        });

        alcohol.setBackground(new java.awt.Color(255, 255, 255));
        alcohol.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        alcohol.setForeground(new java.awt.Color(0, 102, 102));
        alcohol.setText("ALCOHOLIC DRINKS");
        alcohol.setBorder(null);
        alcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcoholActionPerformed(evt);
            }
        });

        sandwich.setBackground(new java.awt.Color(255, 255, 255));
        sandwich.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        sandwich.setForeground(new java.awt.Color(0, 102, 102));
        sandwich.setText("SANDWICH");
        sandwich.setBorder(null);
        sandwich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sandwichMouseClicked(evt);
            }
        });

        shakes.setBackground(new java.awt.Color(255, 255, 255));
        shakes.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        shakes.setForeground(new java.awt.Color(0, 102, 102));
        shakes.setText("SHAKES");
        shakes.setBorder(null);
        shakes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shakesMouseClicked(evt);
            }
        });

        dessert.setBackground(new java.awt.Color(255, 255, 255));
        dessert.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        dessert.setForeground(new java.awt.Color(0, 102, 102));
        dessert.setText("DESSERTS");
        dessert.setBorder(null);
        dessert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dessertMouseClicked(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 255));
        jButton8.setText("Logout");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shakes, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dessert, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soft, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meals, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soft, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dessert, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shakes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(jButton8)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mealsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsMouseClicked
        // TODO add your handling code here:
        Meals obj = new Meals();
        obj.setVisible(true);
        obj.pack();
        this.dispose();
    }//GEN-LAST:event_mealsMouseClicked

    private void softMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_softMouseClicked
        // TODO add your handling code here:
        SoftDrinks obj = new SoftDrinks();
        obj.setVisible(true);
        obj.pack();
        this.dispose();
    }//GEN-LAST:event_softMouseClicked

    private void shakesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shakesMouseClicked
        // TODO add your handling code here:
        Shakes obj = new Shakes();
        obj.setVisible(true);
        obj.pack();
        this.dispose();
    }//GEN-LAST:event_shakesMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
         Login_page hh=new Login_page();
        hh.setVisible(true);
        hh.pack();
        this.dispose();
    }//GEN-LAST:event_jButton8MouseClicked

    private void mealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealsActionPerformed

    private void alcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcoholActionPerformed
        // TODO add your handling code here:
        AlcoholicDrinks obj =new AlcoholicDrinks();
        obj.setVisible(true);
        obj.pack();
        this.dispose();
    }//GEN-LAST:event_alcoholActionPerformed

    private void dessertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dessertMouseClicked
        // TODO add your handling code here:
        Desserts obj =new Desserts();
        obj.setVisible(true);
        obj.pack();
        this.dispose();
    }//GEN-LAST:event_dessertMouseClicked

    private void sandwichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sandwichMouseClicked
        // TODO add your handling code here:
        Sandwich obj=new Sandwich();
        obj.setVisible(true);
        obj.pack();
        this.dispose();
    }//GEN-LAST:event_sandwichMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alcohol;
    private javax.swing.JButton dessert;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton meals;
    private javax.swing.JButton sandwich;
    private javax.swing.JButton shakes;
    private javax.swing.JButton soft;
    // End of variables declaration//GEN-END:variables
}
